/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import model.CalculadorAluguel;
import modelo.Calc;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.ValueSource;
	
class AppTest {    

	CalculadorAluguel aluguel = new CalculadorAluguel(500);
	
//	dia 0 - value: 0, result: -1 
//	dia 1 - value: 1, result: 450 
//	dia 2 - value: 2, result: 450
//	dia 3 - value: 3, result: 450
//	dia 4 - value: 4, result: 450
//	dia 5 - value: 5, result: 450
//	dia 6 - value: 6, result: 475
	
	@ParameterizedTest
	@CsvSource(value={"0:-1", "1:450", "2:450", "3:450", "4:450", "5:450", "6:475"}, delimiter = ':')
	public void dia0(int value, int res){
	    assertEquals(res, aluguel.calcAluguel(value));
	}
	
	
}
