/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import model.CalculadorAluguel;
import modelo.Calc;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.ValueSource;
	
//@TestInstance(Lifecycle.PER_CLASS)
class AppTest {    
//	public double valor;
//	public AppTest() {
//		valor = Math.random();
//	}

	CalculadorAluguel aluguel = new CalculadorAluguel(500);
	
	@ParameterizedTest
	@CsvSource(value={"1:450", "0:-1"}, delimiter = ':')
	public void dia0(int value, int res){
	    assertEquals(res, aluguel.calcAluguel(value));
	}

//	@ParameterizedTest
//	@ValueSource(ints= {1,2,3,4,5})
//	public void testCase01(int x) {
//		Calc c = new Calc();
//		assertEquals(x*x, c.quadrado(x));
//	}
//	
//	
//	@Disabled
//	@Test
//	public void testCase02() {
//		System.out.println(valor);
//		assertEquals(1, 2);
//	}
}


//
//CalculadorAluguel aluguel = new CalculadorAluguel(500);
//
//// Até o 5º Dia do Mês tem desconto de 10% sobre 500
////--------------------------------
//// Extremo do DIA 1 (0,1,2)
////--------------------------------
//@Test
//public void dia0()
//{
//    //Dia 0 Retorna Invalido: -1.0
//    assertEquals(-1, aluguel.calcAluguel(0), 0.01);
//}
//
//@Test
//public void dia1()
//{
//    assertEquals(450, aluguel.calcAluguel(1), 0.01);
//}
//
//@Test
//public void dia2()
//{
//    assertEquals(450, aluguel.calcAluguel(2), 0.01);
//}
//
//// Até o 5º Dia do Mês tem desconto de 10% sobre 500
////--------------------------------
//// Extremo do DIA 5 (4,5,6)
////--------------------------------
//@Test
//public void dia4()
//{
//    assertEquals(450, aluguel.calcAluguel(4), 0.01);
//}
//
//@Test
//public void dia5()
//{
//    assertEquals(450, aluguel.calcAluguel(5), 0.01);
//}
//
////Bug inserido pelo Professor no arquivo JAR
//@Test
//public void dia6()
//{
//    //Dia 6 Retorna BUG: 475.02
//    assertEquals(475, aluguel.calcAluguel(6), 0.01);
//}
//
//// Até o 10º Dia do Mês tem desconto de 5% sobre 500
////--------------------------------
//// Extremo do DIA 10 (9,10,11)
////--------------------------------
//@Test
//public void dia9()
//{
//    assertEquals(475, aluguel.calcAluguel(9), 0.01);
//}
//
//@Test
//public void dia10()
//{
//    assertEquals(475, aluguel.calcAluguel(10), 0.01);
//}
//
//@Test
//public void dia11()
//{
//    assertEquals(500, aluguel.calcAluguel(11), 0.01);
//}
//
//// Até o 15º Dia do Mês o valor é normal de 500
////--------------------------------
//// Extremo do DIA 15 (14,15,16)
////--------------------------------
//@Test
//public void dia14()
//{
//    assertEquals(500, aluguel.calcAluguel(14), 0.01);
//}
//@Test
//public void dia15(){
//    //Dia 15 Retorna BUG: 510.0
//    assertEquals(500, aluguel.calcAluguel(15), 0.01);
//}
//@Test
//public void dia16(){        
//    assertEquals(510.25, aluguel.calcAluguel(16), 0.01);
//}
//
////--------------------------------
//// Extremo do DIA 31 (30,31,32)
////--------------------------------
//@Test
//public void dia30(){
//    assertEquals(513.75, aluguel.calcAluguel(30), 0.01);
//}
//
//@Test
//public void dia31(){
//    //Dia 31 Retorna BUG: 513,75
//    assertEquals(514, aluguel.calcAluguel(31), 0.01);
//}
//
//@Test
//public void dia32(){
//    assertEquals(-1, aluguel.calcAluguel(32), 0.01);
//}

